CREATE TABLE dbo.RefereeEmail
(
	RefereeId UNIQUEIDENTIFIER NOT NULL,
	EmailTypeId SMALLINT NOT NULL,
	IsActive BIT NOT NULL,
	IsDefault BIT NOT NULL,
	DisplayOrder TINYINT NOT NULL,
	ValidFrom DATETIME2(7) GENERATED ALWAYS AS ROW START HIDDEN,
	ValidTo DATETIME2(7) GENERATED ALWAYS AS ROW END HIDDEN,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = History.RefereeEmail));
GO
